# AndroidX kütüphanelerinin modern yapıda çalışmasını zorunlu kılar
android.useAndroidX=true

# Eski kütüphaneleri otomatik olarak AndroidX mimarisine dönüştürür
android.enableJetifier=true

# Derleme performansını artırmak için hafıza optimizasyonu (İsteğe bağlı ama Actions için önerilir)
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

